on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: 'The tag of the release'
        required: true
      runs-on:
        type: string
        description: 'The runner to use for the workflow'
        required: false
        default: 'ubuntu-latest'

jobs:
  retag:
    name: Retag container image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag image
        run: |
          sha=$(git rev-list -n 1 ${{ inputs.tag }})
          docker pull ghcr.io/${{ github.repository }}:"${sha}"
          tag=$(echo "${{ inputs.tag }}" | tr -d 'v')
          docker image tag ghcr.io/${{ github.repository }}:"${sha}" ghcr.io/${{ github.repository }}:"${tag}"
          docker push ghcr.io/${{ github.repository }}:"${tag}"